[project]
name = "Neural_Network_From_Scratch"
version = "0.1.0"
description = "This streamlit app showcases various neural network architectures implemented from scratch using numpy."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.40.2",
]
